web/swhweb/urls.py
from django.contrib import admin
from django.urls import path, include

# Import the views
from . import views

# The name parameter is to reference a page in html
# The first string is the actual url directory
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("license/", views.license, name="license"),
    path("db/reset", views.reset_db, name="reset_db"),
    path("system/", include("system.urls")),
]

web/system/urls.py
from django.urls import path
from . import views

# Add a namespace to differentiate names of views between different apps
app_name = "sys"

# These urls are all proceeded by '/system'
urlpatterns = [
    # path('', views.home, name='home'),
    path(
        "", views.config_home, name="home"
    ),  # Redirect the system home page to the config home page
    # Component views
    path("component/", views.comp_list, name="comp_list"),
    path("component/<component_id>/", views.comp_detail, name="comp_detail"),
    path("component/<component_id>/edit/", views.comp_edit, name="comp_edit"),
    path("component/<component_id>/form/", views.comp_form, name="comp_form"),
    path(
        "component/<component_id>/add_par/",
        views.comp_add_par,
        name="comp_add_par",
    ),
    path(
        "component/<component_type>/create/",
        views.comp_create,
        name="comp_create",
    ),
    path(
        "component/<component_id>/delete/",
        views.comp_delete,
        name="comp_delete",
    ),
    # Climate views
    path("climate/populate/", views.climate_populate, name="climate_populate"),
    # Project views
    path("project/", views.proj_list, name="proj_list"),
    path("project/create/", views.proj_create, name="proj_create"),
    path(
        "project/<project_id>/delete/", views.proj_delete, name="proj_delete"
    ),
    path(
        "project/<project_id>/set_name/",
        views.proj_set_name,
        name="proj_set_name",
    ),
    path("project/<project_id>/edit/", views.proj_edit, name="proj_edit"),
    path("project/<project_id>/form/", views.proj_form, name="proj_form"),
    # Configuration views
    path("configuration/", views.config_home, name="config_home"),
    path(
        "configuration/<configuration_id>/set_name/",
        views.config_set_name,
        name="config_set_name",
    ),
    path(
        "configuration/<configuration_id>/set_climate/<climate_id>/",
        views.config_set_climate,
        name="config_set_climate",
    ),
    path(
        "configuration/<configuration_id>/set_project/<project_id>/",
        views.config_set_project,
        name="config_set_project",
    ),
    path(
        "configuration/<configuration_id>/add_component/<component_id>/",
        views.config_add_component,
        name="config_add_component",
    ),
    path(
        "configuration/<configuration_id>/remove_component/<component_id>/",
        views.config_remove_component,
        name="config_remove_component",
    ),
    path(
        "configuration/<configuration_type>/create/",
        views.config_create,
        name="config_create",
    ),
    path(
        "configuration/<configuration_id>/delete/",
        views.config_delete,
        name="config_delete",
    ),
    path(
        "configuration/<configuration_id>/invoke/",
        views.config_invoke,
        name="config_invoke",
    ),
    # Visualization views
    path("visualization/list", views.vi_list, name="vi_list"),
    path(
        "visualization/<configuration_id>/plot", views.vi_plot, name="vi_plot"
    ),
]

web/system/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.db import IntegrityError
from django.conf import settings

# Imports for Django application
from .models import Component, Configuration, Climate, Project
from .functions import (
    Map,
    str2dict,
    load_weather,
    load_loads_indiv,
    store_pickle,
    load_pickle,
    delete_pickle,
    create_plot,
    create_filename_pickle,
    get_climate_zone_name,
    create_load,
)
from .functions import SYSTEM_LABELS as s
from .functions import CONSUMER_LABELS as c

# For logging
import logging

log = logging.getLogger(__name__)

# *hg Move to functions.py
from mswh.comm.sql import Sql
from mswh.system.source_and_sink import SourceAndSink


"""
=================================
System views
=================================
"""

# Show the system home page
def home(request):
    return render(request, "system/home.html")


"""
=================================
Component views
=================================
"""

# Show the components home page
def comp_list(request):
    # Get a list containing a list of components for each component class with the class name and a list of component type and readable name
    # Output form: [ ['component_class1', ['comp1', 'Component 1 - Readable']], ['component_class2', ['comp2', 'Component 2 - Readable']] ]
    types = Map().get_component_choices()

    # Retrieve a list of all Component objects in the DB
    components = Component.objects.all()

    # Define data to be passed to the template
    data = {"footer": settings.FOOTER, "components": components, "types": types}

    return render(
        request,
        "system/component/list.html",
        data,
    )


# Show the detail view for the given component
def comp_detail(request, component_id):
    # Retrieve the requested component from the DB
    component = get_object_or_404(Component, pk=component_id)

    # Define data to be passed to the template
    data = {"footer": settings.FOOTER, "component": component}

    return render(
        request, "system/component/detail.html", data
    )


# Show the edit view for the given component
def comp_edit(request, component_id):
    # Retrieve the requested component from the DB
    component = get_object_or_404(Component, pk=component_id)

    # Define data to be passed to the template
    data = {"footer": settings.FOOTER, "component": component}

    return render(
        request, "system/component/edit.html", data
    )


# Create new component
def comp_create(request, component_type):
    Component.objects.create_component(
        name=s[component_type], type=component_type
    )
    return redirect("sys:comp_list")


# Delete a component and return to component home screen
def comp_delete(request, component_id):
    # Retrieve the requested component from the DB
    component = get_object_or_404(Component, pk=component_id)
    component.delete()
    return redirect("sys:comp_list")


# Process the input from the form
def comp_form(request, component_id):
    # Retrieve the requested component from the DB
    component = get_object_or_404(Component, pk=component_id)
    errors = []
    par = dict()
    i = 0

    # Retrieve form entries from edit template and strip leading and trailing spaces
    # If value is not found, use 'undefined'
    name = request.POST.get("name", "undefined").lstrip().rstrip()
    description = (
        request.POST.get("description", "undefined").lstrip().rstrip()
    )
    size = request.POST.get("size", "1.0").lstrip().rstrip()

    # Retrieve all parameters
    while True:
        key = request.POST.get("param_key-{}".format(i), "undefined")
        val = request.POST.get("param_val-{}".format(i), "undefined")
        i += 1
        # Break the query as soon as all parameters have been retrieved
        if key == "undefined":
            break
        # If key is empty or only whitespace(s), this results in the deletion of the paramter
        if key != "" and not key.isspace():
            # First remove leading and trailing spaces
            key = key.lstrip().rstrip()
            if key not in par:
                par[key] = val
            else:
                errors.append("Key '{}' appears more than once.".format(key))

    # Cycle through retrieved parameters for checks and conversions
    for key in par:
        # Check if value is of type int or float and convert it if yes
        try:
            par[key] = int(par[key])
        except Exception:
            try:
                par[key] = float(par[key])
            except Exception:
                # This means that par[key] will be stored as string
                # Check if it is empty or only whitespace(s)
                if par[key] == "" or par[key].isspace():
                    errors.append(
                        "Value of '{}' cannot be empty or only whitespace(s).".format(
                            key
                        )
                    )
                # Strip leading and tailing spaces
                par[key] = par[key].lstrip().rstrip()

    # Check if name is empty
    if name == "" or name.isspace():
        errors.append("Name field cannot be empty or only whitespace(s).")

    # Check if new component name does already exist in DB
    if Component.objects.filter(name=name).count() and name != component.name:
        errors.append("Object with the name '{}' already exists.".format(name))

    # Check if description is empty
    if description == "" or description.isspace():
        errors.append(
            "Description field cannot be empty or only whitespace(s)."
        )

    # Check if size is empty
    if size == "":
        errors.append("Size field cannot be empty.")
    else:
        # Check if size is of type float if not empty
        try:
            size = float(size)
        except Exception:
            errors.append("Size field must contain float value.")

    # Check other stuff and add it to the list of errors
    # if <check_for_error>:
    #    errors.append('Error message')

    # If there exist errors, display an error message for each
    if len(errors) > 0:
        return render(
            request,
            "system/component/edit.html",
            {
                "component": component,
                "errors": errors,
            },
        )
    else:
        # Convert the parameters to a string for storage in DB
        params = repr(par)

        # Updates retrieved values to object in DB
        Component.objects.filter(pk=component_id).update(
            name=name,
            params=params,
            description=description,
            size=size,
        )

        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(
            reverse("sys:comp_detail", args=(component_id,))
        )


# Show the edit view for the given component
def comp_add_par(request, component_id):

    # Retrieve the requested component from the DB
    component = get_object_or_404(Component, pk=component_id)

    params = str2dict(component.params)

    # Add parameters
    i = 2
    while True:
        if "param" not in params:
            params["param"] = "undefined"
            break
        elif "param_{}".format(i) not in params:
            params["param_{}".format(i)] = "undefined"
            break
        else:
            i += 1

    # Store new parameters in the DB
    Component.objects.filter(pk=component_id).update(
        params=repr(params),
    )

    # Return to the edit page
    return HttpResponseRedirect(reverse("sys:comp_edit", args=(component_id,)))


"""
=================================
Climate views
=================================
"""

# Populate all climates retrieved from external database
def climate_populate(request):

    # Use path to SWH database defined in settings.py
    swh_db_path = settings.SWH_DATABASE
    log.info('Using SWH database "{}"'.format(swh_db_path))

    db = Sql(swh_db_path)
    log.info("Connected to database.")

    try:
        inputs = db.tables2dict(close=True)
        log.info("Converted sql to pandas DataFrame.")
    except:
        msg = "Failed to read input tables from {}."
        log.info(msg.format(inputs))

    weather = SourceAndSink(input_dfs=inputs)
    log.info("Created SourceAndSink object")

    # Delete all previously stored climate objects before populating them
    n_climate_zones = Climate.objects.all().count()
    if n_climate_zones > 0:
        Climate.objects.all().delete()
        log.info(
            "Deleted {} Climate object(s) from database.".format(
                n_climate_zones
            )
        )
        n_climate_zones = 0

    # Use climate data source as defined in settings.py
    data_source = settings.CLIMATE_DATA_SOURCE

    # Cycle from 1 to 16 (these are the climate zone IDs in the external database)
    for climate_zone_id in range(1, 17):

        climate_zone_id_str = "{:02d}".format(climate_zone_id)

        climate_data = weather.irradiation_and_water_main(
            climate_zone_id_str,
            method="isotropic diffuse",
            weather_data_source=data_source,
        )

        climate = Climate.objects.create_climate(
            name=get_climate_zone_name(climate_zone_id_str),
            climate_zone=climate_zone_id_str,
            data_source=data_source,
        )
        log.info("\nCreated Climate object {} successfully.".format(climate))

        climate.populate_data(climate_data)
        log.info(
            "Populated data of Climate object {} successfully.".format(climate)
        )

        n_climate_zones += 1

    msg = "\nPopulated {} climate zones.".format(n_climate_zones)
    log.info(msg)

    return redirect("sys:config_home")


"""

web/system/templates/system/project/edit.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'icon/favicon.ico'%}" />

    <title>Edit</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    {% comment %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFn$
    {% endcomment %}

    <!-- Custom styles for this template -->
    <link href="{% static 'css/sticky-footer-navbar.css' %}" rel="stylesheet">

  </head>

  <body>

    <header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="{% url 'home' %}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'sys:config_home' %}">Configurations</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'sys:comp_list' %}">Components</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'sys:proj_list' %}">Projects</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'sys:vi_list' %}">Visualization</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'license' %}">License</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>

    <!-- Begin page content -->
    <main role="main" class="container">
      <h1 class="my-3">{{ project.name }}</h1>
      <h4>Households</h4>
      <!-- Form to edit model elements-->
      <form class="needs-validation" action="{% url 'sys:proj_form' project.id %}" method="post" novalidate>
        {% csrf_token %}

        <table class="table table-bordered table-striped col col-6">
          <thead>
            <tr class="table-primary text-center">
              <th scope="col">ID</th>
              <th scope="col">Occupancy</th>
              <th scope="col">At Home</th>
            </tr>
          </thead>
          <tbody>
            {% for key, value in component.get_params.items %}
              <div class="row">
                <div class="col">
                  <input type="text" class="form-control" name="param_key-{{forloop.counter0}}" placeholder="Insert parameter key here." value="{{ key }}" maxlength="255">
                </div>
                <div class="col col-lg-3 col-md-4 col-sm-6 mb-3">
                  <input type="text" class="form-control" name="param_val-{{forloop.counter0}}" placeholder="Insert parameter value here." value="{{ value }}" maxlength="255">
                </div>
              </div>
            {% endfor %}

            {% for household, setup in project.get_households.items %}
            <tr class="text-center">
              <td>
                {{ household }}
              </td>
              <td>
                <input type="number" min="1" max="6" class="form-control" name="occ-{{forloop.counter0}}" placeholder="Insert occupancy here." value="{{ setup.occupancy }}">
              </td>
              <td class="align-center">
                {% if setup.at_home == "y" %}
                  <label class="radio-inline"><input type="radio" name="at_home-{{forloop.counter0}}" value="y" checked>Yes</label>
                  <label class="radio-inline"><input type="radio" name="at_home-{{forloop.counter0}}" id="at_home_no-{{forloop.counter0}}" value="n">No</label>
                {% else %}
                  <label class="radio-inline"><input type="radio" name="at_home-{{forloop.counter0}}" value="y">Yes</label>
                  <label class="radio-inline"><input type="radio" name="at_home-{{forloop.counter0}}" value="n" checked>No</label>
                {% endif %}
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>

        <p class="text-muted">
          <strong>If you click 'Save', the load data is recalculated. This might take a while.</strong><br>
        </p>
        <div class="row px-3">
          <input type="submit" class="btn btn-primary col col-lg-1 col-md-2 col-sm-3 my-3 mr-1" value="Save">
          <a class="btn btn-secondary col col-lg-1 col-md-2 col-sm-3 my-3 ml-1" href="{% url 'sys:proj_list' %}" role="button">Discard</a>
        </div>
      </form>
    </main>

    <footer class="footer">
      <div class="container">
        <span class="text-muted">{{ footer | safe }}</span>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <script src="{% static 'js/jquery-slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% comment %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH$
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46j$
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6Zb$
    {% endcomment %}

  </body>
</html>

web/system/templates/system/project/list.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'icon/favicon.ico'%}" />

    <title>Projects</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    {% comment %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFn$
    {% endcomment %}

    <!-- Custom styles for this template -->
    <link href="{% static 'css/sticky-footer-navbar.css' %}" rel="stylesheet">

  </head>

  <body>

    <header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="{% url 'home' %}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'sys:config_home' %}">Configurations</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'sys:comp_list' %}">Components</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'sys:proj_list' %}">Projects</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'sys:vi_list' %}">Visualization</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'license' %}">License</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>

    <!-- Begin page content -->
    <main role="main" class="container">
      <h1 class="my-3">Projects</h1>
      <p>Each project represents either an individual household (<code>size = 1</code>) or a community with multiple households (<code>size > 1</code>). The occupancy per households can range between 1 and 6. The flag <code>at_home</code> indicates, if the occupants living in the households are at home during the day or not. The <code>Data</code> column indicates, if the hot water load array has been populated for the respective project or not.</p>
      <table class="table table-bordered table-striped">
        <thead>
          <tr class="table-primary text-left">
            <th scope="col" style="width: 40.00%">Name</th>
            <th scope="col" style="width: 5.00%">Size</th>
            <th scope="col" style="width: 25.00%">Occupancy</th>
            <th scope="col" style="width: 25.00%">At Home</th>
            <th scope="col" style="width: 10.00%">Data</th>
          </tr>
        </thead>
        <tbody>
          {% for project in projects %}
          <tr class="text-left">
            <td>
              <p class="my-0">{{ project.name }}</p>
              <a class="small my-0" href="{% url 'sys:proj_edit' project.id %}">Edit</a>
              |
              <a class="small my-0" href="" data-toggle="modal" data-target="#set_name_{{ project.id }}" role="button">
                Rename
              </a>
              <div class="modal fade" id="set_name_{{ project.id }}" tabindex="-1" role="dialog" aria-labelledby="set_name_{{ project.id }}_label" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <form class="needs-validation" action="{% url 'sys:proj_set_name' project.id %}" method="post" novalidate>
                      {% csrf_token %}
                      <div class="modal-header">
                        <h5 class="modal-title" id="set_name_{{ project.id }}_label">Set Project Name</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                        <input type="text" class="form-control" name="name_{{ project.id }}" placeholder="Insert new project name here." value="{{ project.name }}" required/>
                        <input type="hidden" name="project_id_{{ project.id }}" id="hiddenField" value="{{ project.id }}" />
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Discard</button>
                        <button type="button submit" class="btn btn-primary">Save</button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
              |
              <a class="small my-0" href="" data-toggle="modal" data-target="#delete_{{ project.id }}" role="button">
                Delete
              </a>
              <div class="modal fade" id="delete_{{ project.id }}" tabindex="-1" role="dialog" aria-labelledby="delete_{{ project.id }}_label" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="delete_{{ project.id }}_label">Delete {{ project.name }}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body text-left">
                        <p>You are about to delete this project.</p>
                        <p class="text-danger"></p>
                        <div class="alert alert-danger" role="alert">
                          This will also delete the populated data for this project.
                        </div>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <a class="btn btn-danger" href="{% url 'sys:proj_delete' project.id %}" role="button">Delete</a>
                      </div>
                  </div>
                </div>
              </div>
            </td>
            <td class="text-center">
              {{ project.size }}
            </td>
            <td>
              {{ project.occupancy }}
            </td>
            <td>
              {{ project.at_home }}
            </td>
            <td>
              {% if project.data != 'undefined' %}
              Populated
              {% else %}
              Empty
              {% endif %}
            </td>
          </tr>
          {% empty %}
          <tr class="text-left">
            <td colspan="5">
              <p class="text-danger my-3">Found no projects in the database.</p>
            </td>
          </tr>
          {% endfor %}
          <tr class="text-left">
            <td colspan="5">
              <a class="my-3" href="" data-toggle="modal" data-target="#new_project" role="button">
                Create new
              </a>
              <div class="modal fade" id="new_project" tabindex="-1" role="dialog" aria-labelledby="new_project" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <form class="needs-validation" action="{% url 'sys:proj_create' %}" method="post" novalidate>
                      {% csrf_token %}
                      <div class="modal-header">
                        <h5 class="modal-title" id="new_project_label">Create New Project</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                        <div class="container">
                        <table class="table table-borderless">
                          <tbody>
                            <tr class="text-left">
                            <td scope="col" class="align-middle" style="width: 15.00%">Name:</td>
                            <td scope="col" class="align-middle" style="width: 85.00%">
                              <input type="text" class="form-control" name="name" placeholder="Insert project name here." value="" required/>
                            </td>
                            </tr>
                            <tr class="text-left">
                            <td scope="col" class="align-middle" style="width: 15.00%">Size:</td>
                            <td scope="col" class="align-middle" style="width: 85.00%">
                              <input type="number" min="1" class="form-control" name="size" placeholder="Insert project size here." value="1" required/>
                            </td>
                            </tr>
                          </tbody>
                          </table>
                          <p class="text-muted">
                            <strong>If you click 'Create', the load data is calculated. This might take a while.</strong><br>
                          </p>
                          <!-- <input type="number" class="form-control" name="size" placeholder="Insert project size here." value="" required/> -->
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <button type="button submit" class="btn btn-primary">Create</button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </td>
          </tr>
        </tbody>
      </table>

    </main>

    <footer class="footer">
      <div class="container">
        <span class="text-muted">{{ footer | safe }}</span>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <script src="{% static 'js/jquery-slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% comment %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH$
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46j$
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6Zb$
    {% endcomment %}

  </body>
</html>