web/swhweb/urls.py
from django.contrib import admin
from django.urls import path, include

# Import the views
from . import views

# The name parameter is to reference a page in html
# The first string is the actual url directory
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("license/", views.license, name="license"),
    path("db/reset", views.reset_db, name="reset_db"),
    path("system/", include("system.urls")),
]

web/system/urls.py
from django.urls import path
from . import views

# Add a namespace to differentiate names of views between different apps
app_name = "sys"

# These urls are all proceeded by '/system'
urlpatterns = [
    # path('', views.home, name='home'),
    path(
        "", views.config_home, name="home"
    ),  # Redirect the system home page to the config home page
    # Component views
    path("component/", views.comp_list, name="comp_list"),
    path("component/<component_id>/", views.comp_detail, name="comp_detail"),
    path("component/<component_id>/edit/", views.comp_edit, name="comp_edit"),
    path("component/<component_id>/form/", views.comp_form, name="comp_form"),
    path(
        "component/<component_id>/add_par/",
        views.comp_add_par,
        name="comp_add_par",
    ),
    path(
        "component/<component_type>/create/",
        views.comp_create,
        name="comp_create",
    ),
    path(
        "component/<component_id>/delete/",
        views.comp_delete,
        name="comp_delete",
    ),
    # Climate views
    path("climate/populate/", views.climate_populate, name="climate_populate"),
    # Project views
    path("project/", views.proj_list, name="proj_list"),
    path("project/create/", views.proj_create, name="proj_create"),
    path(
        "project/<project_id>/delete/", views.proj_delete, name="proj_delete"
    ),
    path(
        "project/<project_id>/set_name/",
        views.proj_set_name,
        name="proj_set_name",
    ),
    path("project/<project_id>/edit/", views.proj_edit, name="proj_edit"),
    path("project/<project_id>/form/", views.proj_form, name="proj_form"),
    # Configuration views
    path("configuration/", views.config_home, name="config_home"),
    path(
        "configuration/<configuration_id>/set_name/",
        views.config_set_name,
        name="config_set_name",
    ),
    path(
        "configuration/<configuration_id>/set_climate/<climate_id>/",
        views.config_set_climate,
        name="config_set_climate",
    ),
    path(
        "configuration/<configuration_id>/set_project/<project_id>/",
        views.config_set_project,
        name="config_set_project",
    ),
    path(
        "configuration/<configuration_id>/add_component/<component_id>/",
        views.config_add_component,
        name="config_add_component",
    ),
    path(
        "configuration/<configuration_id>/remove_component/<component_id>/",
        views.config_remove_component,
        name="config_remove_component",
    ),
    path(
        "configuration/<configuration_type>/create/",
        views.config_create,
        name="config_create",
    ),
    path(
        "configuration/<configuration_id>/delete/",
        views.config_delete,
        name="config_delete",
    ),
    path(
        "configuration/<configuration_id>/invoke/",
        views.config_invoke,
        name="config_invoke",
    ),
    # Visualization views
    path("visualization/list", views.vi_list, name="vi_list"),
    path(
        "visualization/<configuration_id>/plot", views.vi_plot, name="vi_plot"
    ),
]

web/system/models.py
from django.db import models

import ast
import pandas as pd
import numpy as np

from .functions import (
    Map,
    load_weather,
    check_params,
    str2dict,
    df2dict,
    dict2df,
    simulate_system,
    get_random_project,
    create_load,
)
from .functions import SYSTEM_LABELS as s
from .functions import CONSUMER_LABELS as c

# A manager class for the Component class
class ComponentManager(models.Manager):

    # Create a new component object with given parameters
    def create_component(self, name, type):
        component = self.create(name=name, type=type)
        return component


# Component class
class Component(models.Model):

    # Name of the model
    name = models.CharField(max_length=255, default="undefined")

    # Type of the model
    type = models.CharField(
        max_length=255,
        choices=Map().get_component_choices(),
        default="undefined",
    )

    # Timestamp when the model was created (this value is automatically converted into the correct time zone)
    created = models.DateTimeField(auto_now_add=True)

    # Short description what the model does
    description = models.TextField(
        default="This is an example description what the model is doing, how it is implemented and anything else, which might be of interest to know about the model.\n\nThis can be a rather longer text, since it may contain relevant information about the model, which can't be stored elsewhere."
    )

    # Parameters of the model (stored as dictionary formatted string)
    params = models.TextField(default="{'param' : 123., 'param_2' : 'abc'}")

    # Size of the component
    size = models.FloatField(default=1.0)

    # To use the manager class just call manager functions like this
    # new_comp = Component.objects.create_component(name='new_name', type='new_type')
    objects = ComponentManager()

    # Returns the name of the model
    def __str__(self):
        return self.name

    # Store parameters as string (p is a dictionary)
    def set_params(self, p):
        self.params = repr(p)
        self.save()

    # Load parameters as dictionary
    def get_params(self):
        return ast.literal_eval(self.params)


# A manager class for the Climate class
class ClimateManager(models.Manager):

    # Create a new weather object with given parameters
    def create_climate(self, name, climate_zone, data_source):
        climate = self.create(
            name=name, climate_zone=climate_zone, data_source=data_source
        )
        return climate


# Climate class
class Climate(models.Model):

    # Name of the model
    name = models.CharField(max_length=255, default="undefined")

    # Climate of the model
    climate_zone = models.CharField(max_length=255, default="undefined")

    # Climate data source (cec or tmy3)
    data_source = models.CharField(max_length=255, default="undefined")

    # Weather data of the model (stored as dictionary formatted string)
    data = models.TextField(default="undefined")

    # To use the manager class just call manager functions like this
    # new_weater = Climate.objects.create_climate(name='name', climate_zone=climate_zone, data_source=data_source)
    objects = ClimateManager()

    # Returns the name of the model
    def __str__(self):
        return self.name

    # Populate the data field, using a pandas DataFrame as input parameter
    def populate_data(self, df):
        self.data = str(df2dict(df))
        self.save()

    # Retrieve data from the climate object
    def get_data(self):
        data = ast.literal_eval(self.data)
        return dict2df(data)


# A manager class for the Project class
class ProjectManager(models.Manager):

    # Create a new project object with given parameters
    def create_project(self, name, size):
        project = self.create(name=name, size=size)

        # Create random project set up
        proj = get_random_project(int(size))
        project.set_at_home(proj["at_home"])
        project.set_occupancy(proj["occ"])

        # Populate the data field
        project.populate_data(create_load(proj["occ"], proj["at_home"]))

        return project


# Project class
class Project(models.Model):

    # Name of the model
    name = models.CharField(max_length=255, default="undefined")

    # Occupancy of the households belonging to the project
    # (stored as list formated string)
    occupancy = models.TextField(default="undefined")

    # Flags indicating if the occupants of the households of this project
    # are at home during the day (stored as list formated string)
    at_home = models.TextField(default="undefined")

    # Number of households in the project
    size = models.PositiveSmallIntegerField(default=1)

    # Load data of the model (stored as dictionary formatted string)
    data = models.TextField(default="undefined")

    # To use the manager class just call manager functions like this
    # new_project = Project.objects.create_project(name='name')
    objects = ProjectManager()

    # Returns the name of the model
    def __str__(self):
        return self.name

    # Set the occupancy field, using a list as input parameter
    def set_occupancy(self, lst):
        self.occupancy = str(lst)
        self.save()

    # Get the occupancies from the project object as list
    def get_occupancy(self):
        return ast.literal_eval(self.occupancy)

    # Set the at_home field, using a list as input parameter
    def set_at_home(self, lst):
        self.at_home = str(lst)
        self.save()

    # Get the at_home fields from the project object as list
    def get_at_home(self):
        return ast.literal_eval(self.at_home)

    # Populate the data field, using a pandas DataFrame as input parameter
    def populate_data(self, df):
        # Convert pandas DataFrame to JSON (numpy.array will be converted to Python List)
        self.data = df.to_json()
        self.save()

    # Get dictionary with households' configuration
    def get_households(self):
        households = {}

        # Create a dictionary containing the configuration of the households
        for id in range(self.size):
            households.update(
                {
                    id: {
                        "occupancy": self.get_occupancy()[id],
                        "at_home": self.get_at_home()[id],
                    }
                }
            )

        return households

    # Retrieve data from the project object
    def get_data(self):
        # Create the pandas Dataframe from the json formatted string
        data = pd.read_json(self.data)

        # Convert Python List back to numpy.array
        for i in data["End-Use Load"].index:
            data.at[i, "End-Use Load"] = np.asarray(data["End-Use Load"][i])

        return data


# A manager class for the Model class
class ConfigurationManager(models.Manager):

    # Create a new configuration object with given parameters
    def create_configuration(self, type):
        config = self.create(name=s[type], type=type)
        return config


# Model class
class Configuration(models.Model):

    # Name of the model
    name = models.CharField(max_length=255, default="undefined")

    # Mapping to external system function
    type = models.CharField(
        max_length=255, default="undefined", choices=Map().get_system_choices()
    )

    # Short description what the model does
    description = models.TextField(
        default="This is an example description what the model is doing, how it is implemented and anything else, which might be of interest to know about the model.\n\nThis can be a rather longer text, since it may contain relevant information about the model, which can't be stored elsewhere."
    )

    # List of all components
    components = models.ManyToManyField(Component, blank=True)

    # Climate
    climate = models.ForeignKey(
        "Climate", on_delete=models.SET_NULL, blank=True, null=True
    )

    # Community
    project = models.ForeignKey(
        "Project", on_delete=models.SET_NULL, blank=True, null=True
    )

    # Path to results file
    results_path = models.CharField(max_length=255, default="undefined")

    # To use the manager class just call manager functions like this
    # new_comp = Configuration.objects.create_configuration(type='type')
    objects = ConfigurationManager()

    # Returns the name of the model
    def __str__(self):
        return self.name

    # Set the path to results
    def set_results_path(self, res):
        self.results_path = res
        self.save()

    # Invoke the system simulation
    def invoke_simulation(self, args):
        # Call the simulation function in functions.py
        return simulate_system(args)

    # Check if config is ready for simulation (project and components assigned)
    def check_config(self):
        errors = []

        if not self.climate:
            errors.append("No climate assigned.")
        if not self.project:
            errors.append("No project assigned.")

        # *hg Replace this with a proper check which components are missing if any
        if len(self.components.all()) == 0:
            errors.append("No components assigned.")

        return False if len(errors) == 0 else errors

    # Return all component parameters as pandas DataFrame
    def get_params_pd(self, backup=False):
        # Retrieve all components of this configuration
        component_set = self.components.all()

        if len(list(component_set)) == 0:
            return False

        # Define which components to fetch
        component_list = (
            Map().get_system_backup(system=self.type)
            if backup
            else Map().get_system_components(system=self.type)
        )

        # Create empty DataFrame for holing the parameters
        params_pd = pd.DataFrame(
            data=[], columns=[s["comp"], s["param"], s["param_value"]]
        )

        # Copy component list in new list containing missing components

web/system/templates/system/component/detail.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'icon/favicon.ico'%}" />

    <title>Details</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    {% comment %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFn$
    {% endcomment %}

    <!-- Custom styles for this template -->
    <link href="{% static 'css/sticky-footer-navbar.css' %}" rel="stylesheet">

  </head>

  <body>

    <header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="{% url 'home' %}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'sys:config_home' %}">Configurations</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'sys:comp_list' %}">Components</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'sys:proj_list' %}">Projects</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'sys:vi_list' %}">Visualization</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'license' %}">License</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>

    <!-- Begin page content -->
    <main role="main" class="container">

      <h1 class="mt-3">{{ component.name }}</h1>
      <!--
      <p class="mb-3"><strong>Created: </strong>{{ component.created }}</p>
      -->
      <p class="mb-3"><strong>Type: </strong>{{ component.get_type_display }}</p>

      <h4 class="mt-3">Description</h4>
      <p style="white-space: pre-line;">{{ component.description }}</p>

      <h4 class="mt-3">Size</h4>
      <p class="mb-0">{{ component.size }}</p>
      <p class="mb-3 text-muted small"> The size can have different units or be unitless.</p>

      <h4 class"mt-3">Parameters</h4>
      <!-- List parameters -->
      {% if component.params %}
        <div class="container pl-0">
          <div class="row">
            <div class="col col-lg-6 col-md-8 col-sm-12 my-3">
              <table class="table table-bordered table-striped">
                <thead>
                  <tr class="table-primary">
                    <th scope="col">Key</th>
                    <th scope="col">Value</th>
                  </tr>
                </thead>
                <tbody>
                  {% for key, value in component.get_params.items %}
                    <tr>
                      <td>{{ key }}</td>
                      <td>{{ value }}</td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      {% endif %}
      <div class="row px-3">
        <a class="btn btn-primary col col-lg-1 col-md-2 col-sm-3 mr-1 my-3" href="{% url 'sys:comp_edit' component.id %}" role="button">Edit</a>
        <a class="btn btn-danger col col-lg-1 col-md-2 col-sm-3 my-3 mr-1 ml-1" href="" data-toggle="modal" data-target="#delete_comp" role="button">Delete</a>
        <div class="modal fade" id="delete_comp" tabindex="-1" role="dialog" aria-labelledby="delete_comp_label" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="delete_comp_label">Delete {{ component.name }}</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body text-left">
                  <p>You are about to delete this system component.</p>
                  <p class="text-danger"></p>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                  <a class="btn btn-danger" href="{% url 'sys:comp_delete' component.id %}" role="button">Delete</a>
                </div>
            </div>
          </div>
        </div>
        <!-- <a class="btn btn-secondary col col-lg-1 col-md-2 col-sm-3 ml-1 my-3" onClick="javascript:history.go(-1);" role="button">Back</a> -->
      </div>
    </main>

    <footer class="footer">
      <div class="container">
        <span class="text-muted">{{ footer | safe }}</span>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <script src="{% static 'js/jquery-slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% comment %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH$
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46j$
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6Zb$
    {% endcomment %}

  </body>
</html>

web/system/templates/system/component/edit.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'icon/favicon.ico'%}" />

    <title>Edit</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    {% comment %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFn$
    {% endcomment %}

    <!-- Custom styles for this template -->
    <link href="{% static 'css/sticky-footer-navbar.css' %}" rel="stylesheet">

  </head>

  <body>

    <header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="{% url 'home' %}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'sys:config_home' %}">Configurations</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'sys:comp_list' %}">Components</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'sys:proj_list' %}">Projects</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'sys:vi_list' %}">Visualization</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'license' %}">License</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>

    <!-- Begin page content -->
    <main role="main" class="container">
      <h1 class="my-3">{{ component.name }}</h1>

      <!-- Display an error message if one is provided -->
      <div class="col col-lg-6 col-md-8 col-sm-12 pl-0">
        {% for error in errors %}
          <div class="alert alert-danger" role="alert">
            {{ error }}
          </div>
        {% endfor %}
      </div>

      <!-- Form to edit model elements-->
      <form class="needs-validation" action="{% url 'sys:comp_form' component.id %}" method="post" novalidate>
        {% csrf_token %}
        <h4>Name</h4  >
        <div class="row">
          <div class="col col-lg-6 col-md-8 col-sm-12 mb-3">
            <input type="text" class="form-control" name="name" placeholder="Insert new name here." value="{{ component.name }}" maxlength="255" required>
          </div>
        </div>
        <h4>Description</h4>
        <div class="row">
          <div class="col col-lg-6 col-md-8 col-sm-12 mb-3">
            <textarea type="text" class="form-control" name="description" rows="7" placeholder="Insert the description here." required>{{ component.description }}</textarea>
          </div>
        </div>
        <h4>Size</h4>
        <div class="row">
          <div class="col col-lg-3 col-md-4 col-sm-6 mb-3">
            <input type="number" step="0.1" min="0" class="form-control" name="size" placeholder="Insert the size as float here." value="{{ component.size }}" required>
          </div>
        </div>
        <h4>Parameters</h4>
        {% if component.params %}
          <div class="row">
            <div class="col col-lg-3 col-md-4 col-sm-6">
              <label class="font-weight-bold">Key</label>
            </div>
            <div class="col col-lg-3 col-md-4 col-sm-6">
              <label class="font-weight-bold">Value</label>
            </div>
          </div>
          {% for key, value in component.get_params.items %}
            <div class="row">
              <div class="col col-lg-3 col-md-4 col-sm-6 mb-3">
                <input type="text" class="form-control" name="param_key-{{forloop.counter0}}" placeholder="Insert parameter key here." value="{{ key }}" maxlength="255">
              </div>
              <div class="col col-lg-3 col-md-4 col-sm-6 mb-3">
                <input type="text" class="form-control" name="param_val-{{forloop.counter0}}" placeholder="Insert parameter value here." value="{{ value }}" maxlength="255">
              </div>
            </div>
          {% endfor %}
          <p><a href="{% url 'sys:comp_add_par' component.id %}">Add Parameter</a></p>
          <div class="row">
            <div class="col col-lg-6 col-md-8 col-sm-12">
              <p class="text-muted">
                <strong>Hints:</strong><br>
                Key is always treated as <code>string</code> type.<br>
                Value can be of either <code>int</code>, <code>float</code> or <code>string</code> type.<br>
                To delete a parameter, delete the content of the key field and click 'Save'
              </p>
            </div>
          </div>
        {% endif %}
        <div class="row px-3">
          <input type="submit" class="btn btn-primary col col-lg-1 col-md-2 col-sm-3 my-3 mr-1" value="Save">
          <a class="btn btn-secondary col col-lg-1 col-md-2 col-sm-3 my-3 ml-1" href="{% url 'sys:comp_detail' component.id %}" role="button">Discard</a>
        </div>
      </form>
    </main>

    <footer class="footer">
      <div class="container">
        <span class="text-muted">{{ footer | safe }}</span>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <script src="{% static 'js/jquery-slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% comment %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH$
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46j$
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6Zb$
    {% endcomment %}

  </body>
</html>